import Head from "next/head";
import styles from "../styles/Home.module.css";
import axios from "axios";
import React from "react";
import { useRouter } from "next/router";

export default function Motor() {
  const router = useRouter();

  const [relay1, setRelay1] = React.useState(0);
  const [relay2, setRelay2] = React.useState(0);
  const [relay3, setRelay3] = React.useState(0);
  const [relay4, setRelay4] = React.useState(0);

  var moment = require("moment");

  function clickSend(params) {
    axios
      .post("https://iot-express.herokuapp.com", {
        name: "Dolemon Sushi",
        device: "test",
        relay1: relay1,
        relay2: relay2,
        relay3: relay3,
        relay4: relay4,
      })
      .then((response) => {
        console.log(response);
        router.push("/motor");
      });
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Test JS</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link
          rel="stylesheet"
          href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/css/bootstrap.min.css"
          integrity="sha384-9gVQ4dYFwwWSjIDZnLEWnxCjeSWFphJiwGPXr1jddIhOegiu1FwO5qRGvFXOdJZ4"
          crossOrigin="anonymous"
        />
      </Head>

      <main className={styles.main}>
        <form>
          <div className="form-group">
            <label>Relay 1 {relay1} </label>
            <select
              className="form-control"
              id="exampleFormControlSelect1"
              value={relay1}
              onChange={(e) => setRelay1(e.target.value)}
            >
              <option value="1">Hidup</option>
              <option value="0">Mati</option>
            </select>
          </div>

          <div className="form-group">
            <label>Relay 2 {relay2} </label>
            <select
              className="form-control"
              id="exampleFormControlSelect1"
              value={relay2}
              onChange={(e) => setRelay2(e.target.value)}
            >
              <option value="1">Hidup</option>
              <option value="0">Mati</option>
            </select>
          </div>

          <div className="form-group">
            <label>Relay 3 {relay3} </label>
            <select
              className="form-control"
              id="exampleFormControlSelect1"
              value={relay3}
              onChange={(e) => setRelay3(e.target.value)}
            >
              <option value="1">Hidup</option>
              <option value="0">Mati</option>
            </select>
          </div>

          <div className="form-group">
            <label>Relay 4 {relay4} </label>
            <select
              className="form-control"
              id="exampleFormControlSelect1"
              value={relay4}
              onChange={(e) => setRelay4(e.target.value)}
            >
              <option value="1">Hidup</option>
              <option value="0">Mati</option>
            </select>
          </div>
        </form>

        <button onClick={clickSend}>Test</button>
      </main>

      <footer className={styles.footer}></footer>
    </div>
  );
}
